# MQTT
listener 1883

# WebSocket (optionnel, quand tu exposes 9001)
# listener 9001
# protocol websockets

# Désactive les connexions anonymes
allow_anonymous false

# Fichier des utilisateurs
password_file /mosquitto/data/passwordfile

# Persistance
persistence true
persistence_location /mosquitto/data/

# Logs
log_dest stdout